version: "3.9"

networks:
    siemens_hw:

volumes:
    logs: {}

services:
    web:
        build: .
        restart: always
        ports:
            - "80:80"
        volumes:
            - logs:/var/www/siemens_hw/api/logs:rw
